name: Deploy GitHub Pages

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm install ./home
      - name: Build Home
        run: npm --prefix ./home run build
      - name: Configure Git
        run: |
          git config --global user.name "${{ vars.USERNAME }}"
          git config --global user.email "${{ vars.USEREMAIL }}"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Switch Branch
        run: |
          git branch -D gh-pages || true
          git checkout -b gh-pages
      - name: Deploy Home
        run: |
          git add -f ./home/build/
          git commit -m "gh-pages deploy"
      - name: Deploy Push
        run: |
          git push origin gh-pages
